### Create user
POST http://localhost:3003/users/create
Content-Type: application/json

{
    "name": "user6",
    "email": "user6@email.com",
    "password": "123456789"
}

### Get all users
GET http://localhost:3003/users/getusers
Content-Type: application/json

### Create post
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo":"https://picsum.photos/150",
    "description":"Post6",
    "type":"event",
    "authorId":"01717209-d764-4450-a83e-c47a31cd0ec9"
}

### Get post info
GET http://localhost:3003/post/getpost/1481c540-c3fc-48bb-92f4-cc57ed43af58
Content-Type: application/json

### Create friendship
POST http://localhost:3003/friendship/create
Content-Type: application/json

{
    "userOneId": "99c2e65d-d096-4566-abc7-b155e8549f0f",
    "userTwoId": "98fd03a5-b9ec-45d1-85e2-71f965f890e1"
}

### Delete friendship
DELETE http://localhost:3003/friendship/delete
Content-Type: application/json

{
    "userOneId": "23ee5820-8bc6-409b-822a-e65edae4ce0e",
    "userTwoId": "98fd03a5-b9ec-45d1-85e2-71f965f890e1"
}